import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'fr_FR': {
          'hello': 'bonjour',
          'Powered by ': 'Alimenté par',
          'Login': 'Connexion',
          'Phone Number': 'Numéro de téléphone',
          'MOBILE': 'Entrez votre mobile pour continuer',
          'Enter Otp': 'Entrez OTP',
          'RESEND': 'Renvoyer',
          'Name': 'Nom',
          'Enter Your Name': 'Entrez votre nom',
          'Google Sign In': 'Connexion Google',
          'Email ID': 'Identifiant de messagerie',
          'Mobile': 'Numéro de téléphone',
          'Pin Code': 'Code PIN',
          'Country': 'Pays',
          'personal Information': 'Renseignements personnels',
          'Enter your PinCode': 'Entrez votre Code PIN',
          'Enter your country': 'Entrez votre pays',
          'Save': 'sauvegarder',
          'Cancel': 'Annuler',
          'Choose Your Language': 'Choisissez votre langue',
        },
        'ko_KR': {
          'hello': '안녕하세요',
          'Powered by ': '에 의해 구동',
          'Login': '로그인',
          'Phone Number': '전화 번호',
          'MOBILE': '계속하려면 모바일을 입력하세요',
          'Enter Otp': '일회용 비밀번호 입력',
          'RESEND': '재전송',
          'Name': '이름',
          'Enter Your Name': '당신의 이름을 입력',
          'Google Sign In': '구글 로그인',
          'Email ID': '이메일 주소',
          'Mobile': '전화 번호',
          'Pin Code': '핀 코드',
          'Country': '국가',
          'personal Information': '개인 정보',
          'Enter your PinCode': '비밀번호를 입력하세요',
          'Enter your country': '국가를 입력하세요',
          'Save': '구하다',
          'Cancel': '취소',
          'Choose Your Language': '당신의 언어를 고르시 오',
        },
        'ja_JP': {
          'hello': 'こんにちは',
          'Login': 'ログインする',
          'Powered by ': '搭載',
          'Phone Number': '電話番号',
          'MOBILE': '続行するには携帯電話を入力してください',
          'Enter Otp': 'ワンタイムパスワードを入力してください',
          'RESEND': '再送',
          'Name': '名前',
          'Enter Your Name': 'あなたの名前を入力してください',
          'Google Sign In': 'Googleサインイン',
          'Email ID': '電子メールID',
          'Mobile': '電話番号',
          'Pin Code': 'ピンコード',
          'Country': '国',
          'personal Information': '個人情報',
          'Enter your PinCode': 'PINコードを入力してください',
          'Enter your country': 'あなたの国を入力してください',
          'Save': '保存',
          'Cancel': 'キャンセル',
          'Choose Your Language': '言語を選択してください',
        },
        'en_US': {
          'hello': 'Hello',
          'Powered by ': 'Powered by',
          'Login': 'Login',
          'Phone Number': 'Phone Number',
          'MOBILE': 'Enter your contact number to continue',
          'Enter Otp': 'Enter Verification code',
          'RESEND': 'Resend',
          'personal Information': 'Personal Information',
          'Name': 'Name',
          'Enter Your Name': 'Enter Your Name, Please',
          'Google Sign In': 'Sign In with Google',
          'Email ID': 'Email ID',
          'Mobile': 'Mobile',
          'Pin Code': 'Pin Code',
          'Country': 'Country',
          'Enter your PinCode': 'Enter your Pin Code',
          'Enter your country': 'Enter your Country',
          'Save': 'Save',
          'Cancel': 'Cancel',
          'Choose Your Language': 'Choose Your Language',
          "something is wrong ": "Something’s wrong ",
          "verfication faild": "verification failed",
          "Please check your phone for the verification code":
              "Please check your phone’s message box for verification code.",
          "verfication faild": "verification failed",
          "Oops... somethings is wrong": "Oops... something went wrong",
          "Oops... somethings is wrong": "Oops... something went wrong",
          "Service": "Service",
          "bodygurad": "Bodyguard",
          "Rent": "Rent",
          "HouseRent": "House Rent",
          "Pay": "Pay",
          "See all": "See All",
          "Accessories": "Accessories",
          "Explore": "Explore more",
          "New In": "Latest Arrivals",
          "NO FILE FOUND": "NO FILES FOUND",
          "MyAccount": "My Account",
          "FAQ'S": "FAQS",
          "ABOUT US": "ABOUT US",
          "TEAMS & CONDITION": "TERMS & CONDITIONS",
          "PRIVACY POLICY": "PRIVACY POLICY",
          "Book An Bodygurad": "Book A Bodyguard",
          "Rent Storage": "Rent Storage Site",
          "Easy Exchange!": "Effortless Exchange!",
          "Easy to Use!": "Easy to Use!"
        },
      };
}
